#spring.application.name=ecom-application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: E-commerce application
    version: 1.0.0